server = "wss://localhost:22905"

[auth]
    type = "DEFAULT"
    id = ""
    token = ""

[announcement]
    max-line-per-chanel = 5
    # When player logs in
    header = ''
    # Placeholder: %channel%
    channel = '["",{"text":"[","bold":true,"color":"gold"},{"text":"%channel%","bold":true,"color":"yellow"},{"text":"]","bold":true,"color":"gold"}]'
    # Placeholder: %start-date% %end-date% %title% %content% %author% %channel%
    text = '["",{"text":" \u25b7","bold":true},{"text":" "},{"text":"%title%","hoverEvent":{"action":"show_text","contents":"%content%"}},{"text":" [","color":"green"},{"text":"%start-date%","color":"aqua"},{"text":" @","color":"green"},{"text":" %author%","color":"dark_aqua"},{"text":"]","color":"green"},{"text":" "}]'
    # New announcement
    text-new = '["",{"text":" \u25b6","bold":true,"color":"red"},{"text":" [\u65b0]","color":"gold"},{"text":" "},{"text":"%title%","color":"yellow","hoverEvent":{"action":"show_text","contents":"%content%"}},{"text":" [","color":"green"},{"text":"%start-date%","color":"aqua"},{"text":" @","color":"green"},{"text":" %author%","color":"dark_aqua"},{"text":"]","color":"green"},{"text":" "}]'
    footer = '["",{"text":"\u6309","color":"gray"},{"keybind":"key.chat","color":"gray"},{"text":"\u663e\u793a\u5168\u90e8\uff0c\u9f20\u6807\u60ac\u6d6e\u67e5\u770b\u8be6\u7ec6\u5185\u5bb9\u3002\u4f7f\u7528","color":"gray"},{"text":"/ua","color":"yellow"},{"text":"\u6307\u4ee4\u53ec\u5524\u6b64\u5217\u8868\u3002","color":"gray"}]'
    empty = '{"text":" (\u7a7a)"}'
    # When receiving new announcement broadcast
    # Placeholder: %start-date% %end-date% %title% %content% %author% %channel%
    broadcast-text-new = '["",{"text":"[\u65b0\u901a\u77e5]","color":"gold"},{"text":" "},{"text":"%title%","color":"yellow","hoverEvent":{"action":"show_text","contents":"%content%"}},{"text":" [","color":"green"},{"text":"%start-date%","color":"aqua"},{"text":" @","color":"green"},{"text":" %author%","color":"dark_aqua"},{"text":"]","color":"green"},{"text":" "}]'